// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)
FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByClientId = `-- name: CountProjectsByClientId :one
SELECT COUNT(*)
FROM projects
WHERE client_id = $1
`

func (q *Queries) CountProjectsByClientId(ctx context.Context, clientID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByClientId, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsWithUsers = `-- name: CountProjectsWithUsers :one
SELECT COUNT(DISTINCT p.id)
FROM projects p
LEFT JOIN project_user up ON p.id = up.project_id
LEFT JOIN users u ON up.user_id = u.id
`

func (q *Queries) CountProjectsWithUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsWithUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, client_id, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, client_id, status, start_date, end_date, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ClientID    pgtype.Int8 `json:"client_id"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProject = `-- name: CreateUserProject :exec
insert into project_user (user_id, project_id)
values ($1, $2)
`

type CreateUserProjectParams struct {
	UserID    pgtype.Int8 `json:"user_id"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) CreateUserProject(ctx context.Context, arg CreateUserProjectParams) error {
	_, err := q.db.Exec(ctx, createUserProject, arg.UserID, arg.ProjectID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteUserProject = `-- name: DeleteUserProject :exec
delete from project_user
where user_id = $1 and project_id = $2
`

type DeleteUserProjectParams struct {
	UserID    pgtype.Int8 `json:"user_id"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) DeleteUserProject(ctx context.Context, arg DeleteUserProjectParams) error {
	_, err := q.db.Exec(ctx, deleteUserProject, arg.UserID, arg.ProjectID)
	return err
}

const finUsersByProject = `-- name: FinUsersByProject :many
select user_id, project_id
from project_user
where project_id = $1
`

func (q *Queries) FinUsersByProject(ctx context.Context, projectID pgtype.Int8) ([]ProjectUser, error) {
	rows, err := q.db.Query(ctx, finUsersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectUser
	for rows.Next() {
		var i ProjectUser
		if err := rows.Scan(&i.UserID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyProjects = `-- name: FindManyProjects :many
SELECT id, name, description, client_id, status, start_date, end_date, created_at, updated_at
FROM projects
`

func (q *Queries) FindManyProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, findManyProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyProjectsClientWithUsersWithPagination = `-- name: FindManyProjectsClientWithUsersWithPagination :many
SELECT
    p.id,
    p.name,
    p.description,
    p.client_id,
    p.status,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    COALESCE(
            json_agg(
                    json_build_object(
                            'id', u.id,
                            'name', u.name,
                            'email', u.email
                    )
            ) FILTER (WHERE u.id IS NOT NULL),
            '[]'::json
    ) as users
FROM
    projects p
        LEFT JOIN
    project_user up ON p.id = up.project_id
        LEFT JOIN
    users u ON up.user_id = u.id
where p.client_id = $1
GROUP BY
    p.id
ORDER BY
    p.id
LIMIT $3 OFFSET $2
`

type FindManyProjectsClientWithUsersWithPaginationParams struct {
	ClientID pgtype.Int8 `json:"client_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

type FindManyProjectsClientWithUsersWithPaginationRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ClientID    pgtype.Int8      `json:"client_id"`
	Status      string           `json:"status"`
	StartDate   pgtype.Date      `json:"start_date"`
	EndDate     pgtype.Date      `json:"end_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Users       interface{}      `json:"users"`
}

func (q *Queries) FindManyProjectsClientWithUsersWithPagination(ctx context.Context, arg FindManyProjectsClientWithUsersWithPaginationParams) ([]FindManyProjectsClientWithUsersWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, findManyProjectsClientWithUsersWithPagination, arg.ClientID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindManyProjectsClientWithUsersWithPaginationRow
	for rows.Next() {
		var i FindManyProjectsClientWithUsersWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyProjectsWithPagination = `-- name: FindManyProjectsWithPagination :many
SELECT id, name, description, client_id, status, start_date, end_date, created_at, updated_at
FROM projects
WHERE id > 0
ORDER BY id
LIMIT $2 OFFSET $1
`

type FindManyProjectsWithPaginationParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) FindManyProjectsWithPagination(ctx context.Context, arg FindManyProjectsWithPaginationParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, findManyProjectsWithPagination, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyProjectsWithUsers = `-- name: FindManyProjectsWithUsers :many
SELECT
    p.id,
    p.name,
    p.description,
    p.client_id,
    p.status,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', u.id,
                'name', u.name,
                'email', u.email
            )
        ) FILTER (WHERE u.id IS NOT NULL),
        '[]'::json
    ) as users
FROM
    projects p
LEFT JOIN
    project_user up ON p.id = up.project_id
LEFT JOIN
    users u ON up.user_id = u.id
GROUP BY
    p.id
ORDER BY
    p.id
`

type FindManyProjectsWithUsersRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ClientID    pgtype.Int8      `json:"client_id"`
	Status      string           `json:"status"`
	StartDate   pgtype.Date      `json:"start_date"`
	EndDate     pgtype.Date      `json:"end_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Users       interface{}      `json:"users"`
}

func (q *Queries) FindManyProjectsWithUsers(ctx context.Context) ([]FindManyProjectsWithUsersRow, error) {
	rows, err := q.db.Query(ctx, findManyProjectsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindManyProjectsWithUsersRow
	for rows.Next() {
		var i FindManyProjectsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyProjectsWithUsersWithPagination = `-- name: FindManyProjectsWithUsersWithPagination :many
SELECT
    p.id,
    p.name,
    p.description,
    p.client_id,
    p.status,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', u.id,
                'name', u.name,
                'email', u.email
            )
        ) FILTER (WHERE u.id IS NOT NULL),
        '[]'::json
    ) as users
FROM
    projects p
LEFT JOIN
    project_user up ON p.id = up.project_id
LEFT JOIN
    users u ON up.user_id = u.id
GROUP BY
    p.id
ORDER BY
    p.id
LIMIT $2 OFFSET $1
`

type FindManyProjectsWithUsersWithPaginationParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type FindManyProjectsWithUsersWithPaginationRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ClientID    pgtype.Int8      `json:"client_id"`
	Status      string           `json:"status"`
	StartDate   pgtype.Date      `json:"start_date"`
	EndDate     pgtype.Date      `json:"end_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Users       interface{}      `json:"users"`
}

func (q *Queries) FindManyProjectsWithUsersWithPagination(ctx context.Context, arg FindManyProjectsWithUsersWithPaginationParams) ([]FindManyProjectsWithUsersWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, findManyProjectsWithUsersWithPagination, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindManyProjectsWithUsersWithPaginationRow
	for rows.Next() {
		var i FindManyProjectsWithUsersWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProjectById = `-- name: FindProjectById :one
SELECT id, name, description, client_id, status, start_date, end_date, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) FindProjectById(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, findProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProjectWithUsers = `-- name: FindProjectWithUsers :one
SELECT
    p.id,
    p.name,
    p.description,
    p.client_id,
    p.status,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    COALESCE(
        json_agg(
            json_build_object(
                'id', u.id,
                'name', u.name,
                'email', u.email
            )
        ) FILTER (WHERE u.id IS NOT NULL),
        '[]'::json
    ) as users
FROM
    projects p
LEFT JOIN
    project_user up ON p.id = up.project_id
LEFT JOIN
    users u ON up.user_id = u.id
WHERE
    p.id = $1
GROUP BY
    p.id
`

type FindProjectWithUsersRow struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ClientID    pgtype.Int8      `json:"client_id"`
	Status      string           `json:"status"`
	StartDate   pgtype.Date      `json:"start_date"`
	EndDate     pgtype.Date      `json:"end_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Users       interface{}      `json:"users"`
}

func (q *Queries) FindProjectWithUsers(ctx context.Context, projectID int64) (FindProjectWithUsersRow, error) {
	row := q.db.QueryRow(ctx, findProjectWithUsers, projectID)
	var i FindProjectWithUsersRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Users,
	)
	return i, err
}

const findProjectsByClientId = `-- name: FindProjectsByClientId :many
SELECT id, name, description, client_id, status, start_date, end_date, created_at, updated_at
FROM projects
WHERE client_id = $1
`

func (q *Queries) FindProjectsByClientId(ctx context.Context, clientID pgtype.Int8) ([]Project, error) {
	rows, err := q.db.Query(ctx, findProjectsByClientId, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProjectsByClientIdWithPagination = `-- name: FindProjectsByClientIdWithPagination :many
SELECT id, name, description, client_id, status, start_date, end_date, created_at, updated_at
FROM projects
WHERE client_id = $1
ORDER BY id
LIMIT $3 OFFSET $2
`

type FindProjectsByClientIdWithPaginationParams struct {
	ClientID pgtype.Int8 `json:"client_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) FindProjectsByClientIdWithPagination(ctx context.Context, arg FindProjectsByClientIdWithPaginationParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, findProjectsByClientIdWithPagination, arg.ClientID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProjectsByUser = `-- name: FindProjectsByUser :many
select user_id, project_id
from project_user
where user_id = $1
`

func (q *Queries) FindProjectsByUser(ctx context.Context, userID pgtype.Int8) ([]ProjectUser, error) {
	rows, err := q.db.Query(ctx, findProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectUser
	for rows.Next() {
		var i ProjectUser
		if err := rows.Scan(&i.UserID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name        = $1,
    description = $2,
    client_id   = $3,
    status      = $4,
    start_date  = $5,
    end_date    = $6,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, name, description, client_id, status, start_date, end_date, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ClientID    pgtype.Int8 `json:"client_id"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
