// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: temp2.sql

package database

import (
	"context"
)

const findById2 = `-- name: FindById2 :one
select id, name, email, password from users where id = $1
`

func (q *Queries) FindById2(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findById2, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}
