// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: temp.sql

package database

import (
	"context"
)

const findAll = `-- name: FindAll :many
SELECT id, name, email, password FROM users
`

func (q *Queries) FindAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
