-- name: CreateShipment :exec
INSERT INTO shipments (shipment_id,
                       trans,
                       cus_info,
                       mode,
                       origin,
                       origin_ctry,
                       destination,
                       dest_ctry,
                       consignor_code,
                       consignor_name,
                       consignee_code,
                       consignee_name,
                       house_ref,
                       inco,
                       additional_terms,
                       ppd_ccx,
                       goods_description,
                       origin_etd,
                       dest_eta,
                       weight,
                       uq_1,
                       volume,
                       uq_2,
                       loading_meters,
                       chargeable,
                       uq_3,
                       inner,
                       uq_4,
                       outer,
                       uq_5,
                       added,
                       controlling_customer_code,
                       controlling_customer_name,
                       controlling_agent_code,
                       controlling_agent_name,
                       transport_job,
                       brokerage_job,
                       is_master_lead,
                       master_lead_ref,
                       import_broker_code,
                       import_broker_name,
                       export_broker_code,
                       export_broker_name,
                       job_branch,
                       job_dept,
                       local_client_code,
                       local_client_name,
                       job_sales_rep,
                       job_operator,
                       job_status,
                       job_opened,
                       recognized_revenue,
                       recognized_wip,
                       total_recognized_income_rev_wip,
                       recognized_cost,
                       recognized_accrual,
                       total_recognized_expense_cst_acr,
                       job_profit,
                       consol_id,
                       first_load,
                       last_disch,
                       etd_first_load,
                       eta_last_disch,
                       master,
                       vessel,
                       flight_voyage,
                       load,
                       disch,
                       etd_load,
                       eta_disch,
                       send_agent_code,
                       send_agent_name,
                       recv_agent,
                       recv_agent_name,
                       coloaded_with,
                       coloader_name,
                       carrier_code,
                       carrier_name,
                       teu,
                       cntr_count,
                       other,
                       "20f",
                       "20r",
                       "20h",
                       "40f",
                       "40r",
                       "40h",
                       "45f",
                       gen,
                       unrecognized_revenue,
                       unrecognized_wip,
                       unrecognized_cost,
                       unrecognized_accrual,
                       total_revenue_recognized_unrecognized,
                       total_wip_recognized_unrecognized,
                       total_income_recognized_unrecognized_rev_wip,
                       service_level_code,
                       shippers_reference,
                       consignor_city,
                       consignor_state,
                       consignor_postcode,
                       consignee_city,
                       consignee_state,
                       consignee_postcode,
                       consol_atd,
                       consol_ata,
                       job_revenue_recognition_date,
                       direction,
                       local_client_ar_settlement_group_code,
                       local_client_ar_settlement_group_name,
                       overseas_agent_code,
                       overseas_agent_name,
                       job_overseas_agent_ar_settlement_group_code,
                       job_overseas_agent_ar_settlement_group_name,
                       total_cost_recognized_unrecognized,
                       total_accrual_recognized_unrecognized,
                       total_expense_recognized_unrecognized_cst_acr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
        $31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
        $41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
        $51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
        $61, $62, $63, $64, $65, $66, $67, $68, $69, $70,
        $71, $72, $73, $74, $75, $76, $77, $78, $79, $80,
        $81, $82, $83, $84, $85, $86, $87, $88, $89, $90,
        $91, $92, $93, $94, $95, $96, $97, $98, $99, $100,
        $101, $102, $103, $104, $105, $106, $107, $108, $109, $110,
        $111, $112, $113, $114, $115, $116, $117)
